### ISSUE TITLE
Justification and development level frontend

### ISSUE THREAD

**Issue by peter-tanner** [uwasystemhealth/IndEAAv2#11] opened 2022-06-21 13:11 UTC
## What needs to be done?
A reviewer should be able to select a development level (An option from a list of levels), and give written justification for the development level selected in a text field. 

The current system also displays the justifications of coordinators and documents on the side.

**Comment by ivy0305** [comment] 2022-06-24 05:01
Closed as duplicate of #24

**Closed by ivy0305** 2022-06-24 05:01 UTC
