### ISSUE TITLE
Codebase Setup

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#25] opened 2022-06-23 10:10 UTC
## What needs to be done?
Includes:
- [ ] Frontend (React/NextJS, Typescript/Javascript)
- [ ] Backend (Django)
- [ ] Docker
- [ ] Compose files
- [ ] .github

**Comment by frinzekt** [comment] 2022-06-23 11:24
duplicate of #1

**Closed as completed by frinzekt** 2022-06-23 11:24 UTC
